# Generated by Django 6.0.1 on 2026-01-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='pos_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='computer',
            name='pos_y',
            field=models.IntegerField(default=0),
        ),
    ]
