# Generated by Django 6.0.1 on 2026-01-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_computer_pos_x_computer_pos_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='height',
            field=models.PositiveIntegerField(default=700),
        ),
        migrations.AddField(
            model_name='room',
            name='width',
            field=models.PositiveIntegerField(default=1200),
        ),
    ]
