# Generated by Django 6.0.1 on 2026-01-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_room_height_room_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='is_team_leader',
            field=models.BooleanField(default=False),
        ),
    ]
